### ISSUE TITLE
An AADSTS1000031 error

### ISSUE THREAD

**Issue by shyamag001** [microsoft/cross-tenant#41]
Thank you for writing a great script.

An AADSTS1000031 error is recorded when inviting a user on the resource tenant side, even though the migrating application exists on both the Resource Tenant and Target Tenant.

I think that the 1000031 error itself is an error that is logged when the application does not exist in the target or resource tenant.

As shown in the screenshot below, we can register the application for migration in each tenant by executing Admin Consent as a global administrator from the Admin Consent URLs for the Target and Resource tenants output in PowerShell.

![image](https://user-images.githubusercontent.com/41740353/113411241-396fe280-93f0-11eb-956f-a58ad08bc7b6.png)

In this case, since the application exists, I thought there would be no error when I invite a user from the Resource tenant to the Target tenant as a guest user, but in fact, an error was recorded in the URL as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/41740353/113411292-599fa180-93f0-11eb-9aff-a4f2a3ba1401.png)

However, the error was recorded in the URL as shown in the screenshot below. In fact, the mailbox migration was completed even if this error was ignored, so I think it is appropriate that the 1000031 error is not output if the migration application is registered in both tenants.

**Comment by ropow** [comment]
Good morning Shinya,

We are aware of this happening when using the email acceptance and in the message itself it states that you may hit this error and if so, to copy and paste the URL in the browser.

Hopefully in the future we will get a permanent solution for this.

Thanks,

Roman

From: Shinya Yamaguchi ***@***.***>
Sent: Friday, April 2, 2021 4:17 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] An AADSTS1000031 error (#41)


Thank you for writing a great script.

An AADSTS1000031 error is recorded when inviting a user on the resource tenant side, even though the migrating application exists on both the Resource Tenant and Target Tenant.

I think that the 1000031 error itself is an error that is logged when the application does not exist in the target or resource tenant.

As shown in the screenshot below, we can register the application for migration in each tenant by executing Admin Consent as a global administrator from the Admin Consent URLs for the Target and Resource tenants output in PowerShell.

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F41740353%2F113411241-396fe280-93f0-11eb-956f-a58ad08bc7b6.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C1f03e095e1154af18e1608d8f5c8e171%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637529590436166653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ubdWeLjDRhWHDATktzRrvdDZQT%2BLNVMqp9%2FgUnHn7Ow%3D&reserved=0>

In this case, since the application exists, I thought there would be no error when I invite a user from the Resource tenant to the Target tenant as a guest user, but in fact, an error was recorded in the URL as shown in the screenshot below.

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F41740353%2F113411292-599fa180-93f0-11eb-9aff-a4f2a3ba1401.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C1f03e095e1154af18e1608d8f5c8e171%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637529590436176649%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zai1%2FEobpROf6uj1v9jzLSMJToBgLQTX8enhoHi5hXs%3D&reserved=0>

However, the error was recorded in the URL as shown in the screenshot below. In fact, the mailbox migration was completed even if this error was ignored, so I think it is appropriate that the 1000031 error is not output if the migration application is registered in both tenants.

-

**Comment by shyamag001** [comment]
Thank you for your time and comments.
I understand that this issue itself is recognized as a known issue.
If the same event occurs , we will ignore it as long as the migrating application is registered from the Admin Consent URL on both Resource and Target Azure AD tenants.

We hope that this output will be fixed in the future.
