### ISSUE TITLE
You cannot call a method on a null-valued expression - Run-ExchangeSetupForTargetTenant - Line 732

### ISSUE THREAD

**Issue by 1trevor** [microsoft/cross-tenant#53]
This line throws a "You cannot call a method on a null-valued expression" error if there are no errors in the $Error variable or if $Error[0] doesn't contain an ErrorRecord, which is almost always the case. So the script almost always fails on this line.

`$Error[0].Exception.ErrorRecord.FullyQualifiedErrorId.Contains("MaximumConcurrentMigrationLimitExceededException")`

**Comment by ropow** [comment]
Thanks Trevor,

We'll get this fixed.

Roman

From: Trevor ***@***.***>
Sent: Monday, April 26, 2021 9:08 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] You cannot call a method on a null-valued expression - Run-ExchangeSetupForTargetTenant - Line 732 (#53)


This line throws a "You cannot call a method on a null-valued expression" error if there are no errors in the $Error variable or if $Error[0] doesn't contain an ErrorRecord, which is almost always the case. So the script almost always fails on this line.

$Error[0].Exception.ErrorRecord.FullyQualifiedErrorId.Contains("MaximumConcurrentMigrationLimitExceededException")

-

**Comment by RonJaworski** [comment]
Hello. I am experiencing the same issue reported by 1trevor. I'm assuming there is a work around until resolved. Can someone please elaborate on what I need to do to make the script work? Or does it work and the error is just "cosmetic"? Thanks in advance.

**Comment by ropow** [comment]
Ron,

This is a cosmetic error, you can verify this by running Get-OrganizationRelationship and Get-MigrationEndpoint and verifying both were created.

Thanks,

Roman

**Comment by RonJaworski** [comment]
Thanks for the reply, Roman. The way I handled it to have the script continue to run past that point was...

1. Commented out lines 732 through 744.
2. Then I had to change the verification function of the script so that it wouldnt overwrite my changes with the script from the repository. I commented out lines 820 through 829. I copied line 815 through 817 and pasted between 829 and 830. Then I customized the write-host on the first copied line to indicate to me that it was using my version of the script and not the standard from the repository.

This might not be the "correct" way to do it, but it worked. I hope this helps anyone else who might get stuck. I'm really not a powershell guru, I know barely enough to be extremely dangerous; so use this method at your own risk.
