### ISSUE TITLE
Where I need set Location? 

### ISSUE THREAD

**Issue by davidnunes03** [microsoft/cross-tenant#54]
Hi, I'm trying to run the first script from the Microsoft site, they create the resource and key vault, but stop and show this issue:
I run this:

Source: https://docs.microsoft.com/pt-br/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide

.\SetupCrossTenantRelationshipForTargetTenant.ps1 `
 -ResourceTenantDomain xxxxxx`
 -ResourceTenantAdminEmail XXXX@XXXXXX `
 -TargetTenantDomain xxxxxx `
 -ResourceTenantId xxxx `
 -ResourceGroup "Cross-TenantMoves-TESTE-XXX" `
 -KeyVaultName "CrossTesteUCB" `
 -CertificateName "XXXTESTE-XXXXTESTE-cert" `
 -CertificateSubject "CN=XXXTESTE_XXXTEST" `
 -AzureAppPermissions Exchange, MSGraph `
 -UseAppAndCertGeneratedForSendingInvitation `
 -KeyVaultAuditStorageAccountName "t2tstorageaccount" `
 -KeyVaultAuditStorageResourceGroup "Demo" `
 -SubscriptionId xxxxxx `
 -AzureResourceLocation 'West US'

C: \ Script \ SetupCrossTenantRelationshipForTargetTenant.ps1: It is not possible to validate the argument in the 'Location' parameter. The argument is null or empty. Provide an argument that is not null or empty
and try the command again. 

Thankyou.

**Comment by ropow** [comment]
Good evening David. Since you're passing the -KeyVaultAuditStorageResourceGroup parameter you also need to pass -KeyVaultAuditStorageAccountLocation

From: David Nunes ***@***.***>
Sent: Saturday, May 1, 2021 9:00 PM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Where I need set Location? (#54)


Hi, I'm trying to run the first script from the Microsoft site, they create the resource and key vault, but stop and show this issue:
I run this:

Source: https://docs.microsoft.com/pt-br/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpt-br%2Fmicrosoft-365%2Fenterprise%2Fcross-tenant-mailbox-migration%3Fview%3Do365-worldwide&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29675c7604f94fca391d08d90d1ebb02%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637555247920267635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7oY36AezLOjfAyfhQFKKksqS0MHtiU3NIuW9t%2BpivJA%3D&reserved=0>

.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain xxxxxx
-ResourceTenantAdminEmail XXXX@XXXXXX -TargetTenantDomain xxxxxx
-ResourceTenantId xxxx -ResourceGroup "Cross-TenantMoves-TESTE-XXX"
-KeyVaultName "CrossTesteUCB" -CertificateName "XXXTESTE-XXXXTESTE-cert"
-CertificateSubject "CN=XXXTESTE_XXXTEST" -AzureAppPermissions Exchange, MSGraph
-UseAppAndCertGeneratedForSendingInvitation -KeyVaultAuditStorageAccountName "t2tstorageaccount"
-KeyVaultAuditStorageResourceGroup "Demo" -SubscriptionId xxxxxx
-AzureResourceLocation 'West US'

C: \ Script \ SetupCrossTenantRelationshipForTargetTenant.ps1: It is not possible to validate the argument in the 'Location' parameter. The argument is null or empty. Provide an argument that is not null or empty
and try the command again.

Thankyou.

-

**Comment by davidnunes03** [comment]
> Good evening David. Since you're passing the -KeyVaultAuditStorageResourceGroup parameter you also need to pass -KeyVaultAuditStorageAccountLocation From: David Nunes ***@***.***> Sent: Saturday, May 1, 2021 9:00 PM To: microsoft/cross-tenant ***@***.***> Cc: Subscribed ***@***.***> Subject: [microsoft/cross-tenant] Where I need set Location? (#54) Hi, I'm trying to run the first script from the Microsoft site, they create the resource and key vault, but stop and show this issue: I run this: Source: https://docs.microsoft.com/pt-br/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpt-br%2Fmicrosoft-365%2Fenterprise%2Fcross-tenant-mailbox-migration%3Fview%3Do365-worldwide&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29675c7604f94fca391d08d90d1ebb02%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637555247920267635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7oY36AezLOjfAyfhQFKKksqS0MHtiU3NIuW9t%2BpivJA%3D&reserved=0> .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain xxxxxx -ResourceTenantAdminEmail XXXX@XXXXXX -TargetTenantDomain xxxxxx -ResourceTenantId xxxx -ResourceGroup "Cross-TenantMoves-TESTE-XXX" -KeyVaultName "CrossTesteUCB" -CertificateName "XXXTESTE-XXXXTESTE-cert" -CertificateSubject "CN=XXXTESTE_XXXTEST" -AzureAppPermissions Exchange, MSGraph -UseAppAndCertGeneratedForSendingInvitation -KeyVaultAuditStorageAccountName "t2tstorageaccount" -KeyVaultAuditStorageResourceGroup "Demo" -SubscriptionId xxxxxx -AzureResourceLocation 'West US' C: \ Script \ SetupCrossTenantRelationshipForTargetTenant.ps1: It is not possible to validate the argument in the 'Location' parameter. The argument is null or empty. Provide an argument that is not null or empty and try the command again. Thankyou. - You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F54&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29675c7604f94fca391d08d90d1ebb02%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637555247920267635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jsQybypxdulVmS9kMs%2FSKLZQ7883thyK5kqAN3BdxRI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6HGAWOHCT3IZBCLJHTTLTE3JANCNFSM4367I4ZA&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29675c7604f94fca391d08d90d1ebb02%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637555247920277591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2pcuwbVUMuT4Qma4g8WRIQ473O0lAufKyDaRW3Yn8OU%3D&reserved=0>.

Hi ropow! Thanks for answer. Your tip works, but now I have a new problem.

"C: \ Script \ SetupCrossTenantRelationshipForTargetTenant.ps1: It is not possible to validate the argument in the 'SkuName' parameter. The argument "" does not belong to the set
"Standard_LRS; Standard_ZRS; Standard_GRS; Standard_RAGRS; Premium_LRS; Premium_ZRS; Standard_GZRS; Standard_RAGZRS" specified by the ValidateSet attribute. Provide an argument that is in the set and
try the command again. "

I try to set 
-SkuName Standard_GZRS and -KeyVaultAuditStorageAcntSKU 'Standard_GZRS', but dont work. 

Thankyou.

**Comment by ropow** [comment]
David,

Can you try with Standard_GRS

Thanks,

Roman

**Comment by davidnunes03** [comment]
Hi Roman! Thank you for answers and help. It worked here, I investigate the script and found some things that miss.
Thanks
