### ISSUE TITLE
Error with logging in in step 6

### ISSUE THREAD

**Issue by andytuke-jisc** [microsoft/cross-tenant#70]
We have been trying to get the SetupCrossTenantRelationshipForResourceTenant.ps1 script to run. The docs are pretty out of date to the current version but we have been working through it, We are now hitting an issue with it at the point where we have to consent to the application, section 6 in the step by step guide.  We have clicked the link and accepted as a global admin in the target tenant. In Azure we can see the app and it all looks ok. We then get a message where it appears to be trying to get a token so that it can send an email to the admin in the source tenant. We get a log in prompt, we assume its the GA for the target tenant though we have tried both, and when we put in our credentials we get a error dialog as shown in the attachment. In the script we believe this is happening in the function Get-AccessTokenWithUserPrompt as we have put on verbose output and we see the output from line 577
    Write-Verbose "Acquiring token resourceAppIdURI $resourceUri" 
just before the error is raised. At this point the script exits 

Please consent to the app for newcollegeonline.onmicrosoft.com before sending invitation to AdminSource@swindonac.onmicrosoft.com:

C:\Exchange Online Setup\SetupCrossTenantRelationshipForTargetTenant.ps1 : Exception calling "GetResult" with "0" argument(s): "User canceled authentication"
At C:\Exchange Online Setup\CommandLineTarget.ps1:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [SetupCrossTenan...argetTenant.ps1], MethodInvocationException
    + FullyQualifiedErrorId : AdalServiceException,SetupCrossTenantRelationshipForTargetTenant.ps1

PS C:\Exchange Online Setup> 

![Azurereplyurl](https://user-images.githubusercontent.com/67311072/126602161-8c3b210d-c6d6-4754-8e3f-18f0ecb97064.png)

**Comment by ropow** [comment]
Good morning Andy,

Please consent using an InPrivate/Incognito window. There are 2 links, one for target, one for source, and they require logging in with the credentials for that specific tenant.

Thanks,

Roman

From: Andy Tuke ***@***.***>
Sent: Thursday, July 22, 2021 12:29 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Error with logging in in step 6 (#70)


We have been trying to get the SetupCrossTenantRelationshipForResourceTenant.ps1 script to run. The docs are pretty out of date to the current version but we have been working through it, We are now hitting an issue with it at the point where we have to consent to the application, section 6 in the step by step guide. We have clicked the link and accepted as a global admin in the target tenant. In Azure we can see the app and it all looks ok. We then get a message where it appears to be trying to get a token so that it can send an email to the admin in the source tenant. We get a log in prompt, we assume its the GA for the target tenant though we have tried both, and when we put in our credentials we get a error dialog as shown in the attachment. In the script we believe this is happening in the function Get-AccessTokenWithUserPrompt as we have put on verbose output and we see the output from line 577
Write-Verbose "Acquiring token resourceAppIdURI $resourceUri"
just before the error is raised. At this point the script exits

Please consent to the app for newcollegeonline.onmicrosoft.com before sending invitation to ***@***.******@***.***>:

C:\Exchange Online Setup\SetupCrossTenantRelationshipForTargetTenant.ps1 : Exception calling "GetResult" with "0" argument(s): "User canceled authentication"
At C:\Exchange Online Setup\CommandLineTarget.ps1:1 char:1

  *   .\SetupCrossTenantRelationshipForTargetTenant.ps1 `

*           + CategoryInfo          : NotSpecified: (:) [SetupCrossTenan...argetTenant.ps1], MethodInvocationException

*           + FullyQualifiedErrorId : AdalServiceException,SetupCrossTenantRelationshipForTargetTenant.ps1

*

  *

PS C:\Exchange Online Setup>

[Azurereplyurl]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F67311072%2F126602161-8c3b210d-c6d6-4754-8e3f-18f0ecb97064.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C8f182948d4dc422119ed08d94ce26154%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637625357465812383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wL5LzJXRbJGQ06u0AigEbtz0PlSBrfL0ovMR%2FuzLnmQ%3D&reserved=0>

-

**Comment by bas-jisc** [comment]
Hi Roman,

I'm one of the engineers working with Andy on this. I just wanted to note that the script did not provide the links for consent when used with the -ExistingApplicationId parameter. As we already had the app created, what we ended up doing was using the -UseAppAndCertGeneratedForSendingInvitation parameter to skip the part we were having trouble with (where it uses Azure invitation manager to send the invitation) and the invitation email was sent while the script reported successful completion.
However, after the resource tenant admin received the invitation email we found that the link provided to accept the invitation would not work and kept taking us to https://developer.microsoft.com/en-us/graph#. After a bit of playing about trying to get the invitation to work, we eventually just took the common admin consent url and appended the application Id to it (e.g. https://login.microsoftonline.com/common/adminconsent?client_id=<app-id>) and that seemed to take us to the correct page to approve the invitation and create the Enterprise app in the resource (source) tenant.

**Comment by ropow** [comment]
Was it the button that didn't work, or the actual link in the email address? We have had issues with the button not working correctly, which is why we've been including the link as well.

Also, it sounds like this is now resolved?

Thanks,

Roman

**Comment by andytuke-jisc** [comment]
It was both, they asked for an authentication and then immediately took you to a MS Graph developer page.

**Comment by andytuke-jisc** [comment]
Our setup appears good and has verified ok.  The test migration we are trying gives an error

Error: MigrationPermanentException: The target mailbox doesn't have an SMTP proxy matching 'mycollegeonline.mail.onmicrosoft.com'. --> The target mailbox doesn't have an SMTP proxy matching 'mycollegeonline.mail.onmicrosoft.com'.

There's nothing in the documentation saying the mail.onmicrosoft.com address is required.
