### ISSUE TITLE
error sending consent invitation

### ISSUE THREAD

**Issue by Jeberoni** [microsoft/cross-tenant#76]
Getting the following error with the invitation not being able to send -

![image](https://user-images.githubusercontent.com/15256202/128720715-1df3d37f-6505-4bc1-9b44-dafb97ac1696.png)

Removing the -UseAppAndCertGeneratedForSendingInvitation switch results results in the AADSTS50011 error as detailed in the various other issues raised. I have also checked whether I have the target and resource domains backwards, as this was the resolution for one of the issues raised here. 

Switches Used -
SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain <resource domain> -TargetTenantDomain <target domain> -ResourceTenantAdminEmail <resource Tadmin Email> -ResourceTenantId <Resource Tenant ID> -SubscriptionId <Sub ID> -ResourceGroup <"RG Name"> -KeyVaultName <"KV Name"> -CertificateSubject <"Cert CN Name"> -AzureAppPermissions Exchange, MSGraph -AzureResourceLocation <location> -ExistingApplicationId <existing app ID> -UseAppAndCertGeneratedForSendingInvitation

**Comment by ropow** [comment]
Good morning. When receiving the AADSTS50011 error, this is generally a credential issue of an already signed in existing account that does not belong to the target tenant. Can you please use UseAppAndCertGeneratedForSendingInvitation, and make sure that the correct account is being used (clean PSSession).

Thanks,

Roman

From: Jeberoni ***@***.***>
Sent: Monday, August 9, 2021 7:12 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] error sending consent invitation (#76)


Getting the following error with the invitation not being able to send -

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15256202%2F128718365-4eae7e01-52f0-46f9-ba23-41762b190f02.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cc84b9ad29fba44b7ac4708d95b3fb0c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637641151385321779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Cr7WNPTS2bsY6y5wosHkSHCqafhr9mvMsPXzfQw%2BYvU%3D&reserved=0>

Removing the -UseAppAndCertGeneratedForSendingInvitation switch results results in the AADSTS50011 error as detailed in the various other issues raised. I have also checked whether I have the target and resource domains backwards, as this was the resolution for one of the issues raised here.

Switches Used -
SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain -TargetTenantDomain -ResourceTenantAdminEmail -ResourceTenantId -SubscriptionId -ResourceGroup <"RG Name"> -KeyVaultName <"KV Name"> -CertificateSubject <"Cert CN Name"> -AzureAppPermissions Exchange, MSGraph -AzureResourceLocation -ExistingApplicationId -UseAppAndCertGeneratedForSendingInvitation

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F76&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cc84b9ad29fba44b7ac4708d95b3fb0c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637641151385331778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7WoWHrHRDWZ1iRHZHEvdNDX9ZgDJ7p4XexM0OPEqyGY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6AKLWVY2IYPJMD2DBDT37O37ANCNFSM5B2DO3PQ&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cc84b9ad29fba44b7ac4708d95b3fb0c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637641151385341765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T2PPtWy6kIxIXhaiCK9QDvC8Q2Yc6GKcSo8IO0LjFEA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cc84b9ad29fba44b7ac4708d95b3fb0c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637641151385341765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gd8%2Fp6xqvx3fXXGWaJkY7TKsymTQ1RazqEjbGK%2F%2Fihs%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cc84b9ad29fba44b7ac4708d95b3fb0c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637641151385351766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m3YL7tlymPHeokIhEzh4AKjnzQlLk7h0vGQodkYYEVc%3D&reserved=0>.

**Comment by knlp** [comment]
$FIRSTPARTY_POWERSHELL_CLIENTID = "a0c73c16-a7e3-4564-9a95-2bdf47383716"
This produces an error where it cannot find the reply URL, but it is correct. The problem is with the PowerShell Client ID, that has the wrong value. The correct value is below:
$FIRSTPARTY_POWERSHELL_CLIENTID = "1950a258-227b-4e31-a9cf-717495945fc2"

Get rid of script content validation and update the ID, it will work like a charm.
