### ISSUE TITLE
GetAzLocation error? Not in script?

### ISSUE THREAD

**Issue by netxgarrett** [microsoft/cross-tenant#77]
![image](https://user-images.githubusercontent.com/89261365/130250462-b1db71c3-71d3-43ab-a0bd-015bf39cb83b.png)

I dont understand this error as it is not even in the script.

**Comment by ropow** [comment]
Hello, Get-AzLocation is part of the script, this happens during validation.

Before running the script can you please run Connect-AzAccount then run the script and see if this resolves the issue.

Thanks,

Roman

From: netxgarrett ***@***.***>
Sent: Friday, August 20, 2021 7:43 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] GetAzLocation error? Not in script? (#77)


[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89261365%2F130250462-b1db71c3-71d3-43ab-a0bd-015bf39cb83b.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3bc14daaf0b6415095eb08d963e8c0c1%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650673597229539%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CpeyLGlikfcxVNwgQAQSywf%2BKySCxtwK7uGLCga8gds%3D&reserved=0>

I dont understand this error as it is not even in the script.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F77&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3bc14daaf0b6415095eb08d963e8c0c1%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650673597239524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sszkoXK4da57V1PTJzKmHzHGSEepg5rdcgbjlrtRfLg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6HCMBQX72JXSXNATV3T5ZSVZANCNFSM5CQOUXSQ&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3bc14daaf0b6415095eb08d963e8c0c1%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650673597239524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QJAR%2FzwDhqbBffnrfwvG47ju4l7JslddcJ7jTO0zoGY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3bc14daaf0b6415095eb08d963e8c0c1%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650673597249537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XVDifJRLK%2FWdE6Up985UfiHnnT4TYKSZ%2F4duF%2FdsZwA%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3bc14daaf0b6415095eb08d963e8c0c1%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650673597259516%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VkHcixnARlsqpWk8m4wQA6oJ5KA0Py9KX9YHw9n39Ws%3D&reserved=0>.

**Comment by netxgarrett** [comment]
Thank you!
