### ISSUE TITLE
Azlocation validation fail because of multiple AZ Subscriptions.

### ISSUE THREAD

**Issue by wiz508** [microsoft/cross-tenant#81]
"WARNING: TenantId 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx' contains more than one active subscription. First one will be
selected for further use. To select another subscription, use Set-AzContext.

Check-AzurePowershellConnection : A valid Azure location was not specified, please run Get-AzLocation to determine a
valid location."

I do not have full permssion to the first subscription in the azure tenant. 
I've tried connecting before running the script with Connect-AzAccount -Subscription 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx'. 
The subscriptionID is specified as a parameter when running and I have tried to set the context with the Set-AzContext command befor running but it still selects the first  subscription for the validation check and then the script closes.

**Comment by ropow** [comment]
Good morning. The error is due to not providing the parameter -AzureResourceLocation with a proper location, this is causing the script to exit.

Thanks,

Roman

From: wiz508 ***@***.***>
Sent: Tuesday, September 21, 2021 8:31 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Azlocation validation fail becuase of multiple AZ Subscriptions. (#81)


"WARNING: TenantId 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx' contains more than one active subscription. First one will be
selected for further use. To select another subscription, use Set-AzContext.

Check-AzurePowershellConnection : A valid Azure location was not specified, please run Get-AzLocation to determine a
valid location."

I do not have full permssion to the first subscription in the azure tenant.
I've tried connecting before running the script with Connect-AzAccount -Subscription 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx'.
The subscriptionID is specified as a parameter when running and I have tried to set the context with the Set-AzContext command befor running but it still selects the first subscription for the validation check and then the script closes.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F81&data=04%7C01%7CRoman.Powell%40microsoft.com%7C09fd413149a1464a5a5608d97d14bf58%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637678350369847064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vbJlPHxw2Ty4OaE84lKm49ycz4y1aGARaMgRX4tVsqg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6HJALPJ2L4EAGLZ2RTUDCQJNANCNFSM5EOYRMZA&data=04%7C01%7CRoman.Powell%40microsoft.com%7C09fd413149a1464a5a5608d97d14bf58%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637678350369847064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JmkP027MECMzhWU9yhUHogmjB%2B2FNB%2F0vhsfGvedO2M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRoman.Powell%40microsoft.com%7C09fd413149a1464a5a5608d97d14bf58%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637678350369857060%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T6e0eCP%2BshM111exTbvhkA8FNIs9skyPszcGaoUA%2Fx0%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CRoman.Powell%40microsoft.com%7C09fd413149a1464a5a5608d97d14bf58%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637678350369857060%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3iq6kO4sDjKp1FLmZBEvQkEoyfknQ4GbpkI0UTvQdfk%3D&reserved=0>.
