### ISSUE TITLE
connect to the Exchange Online Management module or Exchange Online through basic authentication before running this script!

### ISSUE THREAD

**Issue by eliassader** [microsoft/cross-tenant#85]
When running the SetupCrossTenantRelationshipForTargetTenant.ps1 with its parameters, i am faced with such error, that requires a login technique deprecated by Microsoft
Thank you for your advise

Check-ExchangeOnlinePowershellConnection : Please connect to the Exchange Online Management module or Exchange Online
through basic authentication before running this script!
At D:\ps\SetupCrossTenantRelationshipForTargetTenant.ps1:840 char:5
 Check-ExchangeOnlinePowershellConnection
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
 FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Check-ExchangeOnlinePowershellConnecti
   on

**Comment by ropow** [comment]
Good morning Elias.

Connecting to Exchange Online Management is not deprecated. Please see the following link:

Connect to Exchange Online PowerShell | Microsoft Docs<https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps>

Thanks,

Roman

From: Elias Sader ***@***.***>
Sent: Thursday, September 30, 2021 7:27 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] connect to the Exchange Online Management module or Exchange Online through basic authentication before running this script! (#85)


When running the SetupCrossTenantRelationshipForTargetTenant.ps1 with its parameters, i am faced with such error, that requires a login technique deprecated by Microsoft
Thank you for your advise

Check-ExchangeOnlinePowershellConnection : Please connect to the Exchange Online Management module or Exchange Online
through basic authentication before running this script!
At D:\ps\SetupCrossTenantRelationshipForTargetTenant.ps1:840 char:5
Check-ExchangeOnlinePowershellConnection
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Check-ExchangeOnlinePowershellConnecti
on

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F85&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cd0c3be1dd3124c4d8e4908d9841e6911%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637686088441005024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K%2F6vsLF9C8%2FGQIqsSXLPPwWbphOPZBCB%2BHu6Jak1IkA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6CM7UBRMIJ75XI3ARTUERXUPANCNFSM5FCPHKCQ&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cd0c3be1dd3124c4d8e4908d9841e6911%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637686088441015014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cgFtLfpGcY66KonMoeCp6EGQHmZBaK7v1d9I9vvHDsM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cd0c3be1dd3124c4d8e4908d9841e6911%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637686088441015014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iR7Jsca7YIAIPcfvq5GZmoEiWVcHLPfa5x6biwYndPE%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cd0c3be1dd3124c4d8e4908d9841e6911%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637686088441025008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BP5KZxbNDtJil5zI%2FiyZOKcppPFAcGzfFMVJztrHQPQ%3D&reserved=0>.

**Comment by eliassader** [comment]
Dear Roman,

Using the PowerShell 7.14 solved the issue of the Exchange and lead to the creation of the Azure and the app, and generated the links to be approved by both tenants, after that the prompt asks for "enter when done" to send the invite email to the "source tenant"
Then it is prompting this error in the opened window of sign in:
AADSTS90002: Tenant 'token' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.

Sorry for the inconvenience, your guidance is greatly appreciated
______________________

Elias E. Sader


________________________________

**Comment by ropow** [comment]
Good morning Elias,

Make sure you are signing in with the target tenant credentials. Can you run the script again and see if you get past this step. In the past this has been the resolution.

Thanks,

Roman

**Comment by alpina27** [comment]
I am connected to Exchange online powershell before I Start the Script. I Double checked it with ExOn PS querys.

**Comment by ropow** [comment]
The only thing I can think if you're sure you're connected then, is that you don't the right roles assigned to run New-OrganizationRelationship as this is how we check if you're connected to Exchange:

function Check-ExchangeOnlinePowershellConnection {
    if ($Null -eq (Get-Command New-OrganizationRelationship -ErrorAction SilentlyContinue)) {
        Write-Error "Please connect to the Exchange Online Management module or Exchange Online through basic authentication before running this script!";
    }
}

Please validate that you have access to that cmdlet.

Thanks,

Roman

**Comment by alpina27** [comment]
Hi Roman,
thanks for reply.
That was the tipp, New-Organizationrelationship was not avaible. Reload powershell then it was avaible and works.

Now the next error is

**Verifying that a valid location was specified for Azure 

Check-AzurePowershellConnection : A valid Azure nocation was not specified, pelease run 
Get -Azlocation to determine a valid location.** 

![grafik](https://user-images.githubusercontent.com/12609953/137992844-ce293c43-33da-4333-8719-8e808e1fa5cc.png)

**Comment by alpina27** [comment]
I have set...
PS C:\PowerShell\> .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain source.onmicrosoft.com -ResourceTenantAdmin xxxx@source.onmicrosoft.com -TargetTenantDomain target.onmicrosoft.com -ResourceTenantId xxxxxxx-xxxx-xxxx-xxxx-xxxxx-SubscriptionId xxxxxxx-xxx-xxxxx-xxx-xxxxxxx-ResourceGroup "xxxxxxxMoveRG" -KeyVaultName "adxxxx-TenantMovesVault" -CertificateName "xxxcert" -CertificateSubject "CN=xxxcon" -AzureResourceLocation "West Europe" -AzureAppPermissions Exchange, MSGraph -UseAppAndCertGeneratedForSendingInvitation

I also try to login before Connect-AzAccount and try -AzureResourceLocation "West Europe" and -AzureResourceLocation "WestEurope" like here https://issueexplorer.com/issue/microsoft/cross-tenant/71
